### ISSUE TITLE
Input data XY and Theta files

### ISSUE THREAD

**Issue by palbertomc** [icojb25/TurbineOpti#1]
Hi,
Thank you for sharing this project. I find it very interesting. I am looking at the main file and have the following questions:
What data/variables are expected for the XY data and Theta files used as an input? And in what format should they be organised?

Kind regards,

**Comment by icojb25** [comment]
hi @palbertomc 

thanks for raising the issue - the file format is the Matlab binary format (*.mat). Regarding the data itself,  i will look it up and add it to the Readme.

In terms of what the actual values are, the X data is a matrix of design vectors and Y data is a vector of the corresponding objective function values (for those design vectors). The Theta data is a vector of the kriging model fitting parameters (for each design vector dimension) which corresponding to the kriging weights for each dimension (of the design (X) vectors). 

I will see if i can find some sample data to add as well.

All the best

**Comment by icojb25** [comment]
hi @palbertomc 

I have updated the README with info on the correct file / data formats as well as included a pair of sample .mat files for getting started.

**Comment by palbertomc** [comment]
Hi @icojb25 

Thank you for your answer.
